# The behavior of RuboCop can be controlled via the .rubocop.yml
# configuration file. It makes it possible to enable/disable
# certain cops (checks) and to alter their behavior if they accept
# any parameters. The file can be placed either in your home
# directory or in some project directory.
#
# RuboCop will start looking for the configuration file in the directory
# where the inspected file is and continue its way up to the root directory.
#
# See https://docs.rubocop.org/rubocop/configuration
#

AllCops:
  Include:
    - 'lib/**/*.rb'
    - 'spec/**/*'
    - '*.gemspec'
  Exclude:
    - 'bin/**/*'
    - 'lib/renuo/cli.rb'
    - 'lib/renuo/cli/app/heroku_users'
    - 'lib/renuo/cli/app/fetch_all_emails'
    - 'lib/renuo/cli/app/create_heroku_app'
    - 'vendor/**/*'

Layout/LineLength:
  Max: 120

Naming/FileName:
  Exclude:
  - 'Gemfile'
  - 'Rakefile'

Metrics/BlockLength:
  Exclude:
  - 'Rakefile'
  - '**/*.rake'
  - 'spec/**/*.rb'

Metrics/ClassLength:
  Max: 160

Style/Documentation:
  Enabled: false

Style/NonNilCheck:
  IncludeSemanticChanges: true

Style/FormatStringToken:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GlobalVars:
  Enabled: false

